version: "3.9"
services:
  fastapi_fibonacci:
    image: fastapi-fibonacci
    container_name: fastapi-fibonacci
    build: .
    ports:
      - "8000:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --workers 4
